// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        uint64                 `protobuf:"varint,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient     uint64                 `protobuf:"varint,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Channel       uint64                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *ChatMessage) GetRecipient() uint64 {
	if x != nil {
		return x.Recipient
	}
	return 0
}

func (x *ChatMessage) GetChannel() uint64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CredentialMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialMessage) Reset() {
	*x = CredentialMessage{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialMessage) ProtoMessage() {}

func (x *CredentialMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialMessage.ProtoReflect.Descriptor instead.
func (*CredentialMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialMessage) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CredentialMessage) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type EntityDataMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Health        float32                `protobuf:"fixed32,3,opt,name=health,proto3" json:"health,omitempty"`
	Energy        float32                `protobuf:"fixed32,4,opt,name=energy,proto3" json:"energy,omitempty"`
	XPos          float32                `protobuf:"fixed32,5,opt,name=x_pos,json=xPos,proto3" json:"x_pos,omitempty"`
	YPos          float32                `protobuf:"fixed32,6,opt,name=y_pos,json=yPos,proto3" json:"y_pos,omitempty"`
	ZPos          float32                `protobuf:"fixed32,7,opt,name=z_pos,json=zPos,proto3" json:"z_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDataMessage) Reset() {
	*x = EntityDataMessage{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDataMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDataMessage) ProtoMessage() {}

func (x *EntityDataMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDataMessage.ProtoReflect.Descriptor instead.
func (*EntityDataMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *EntityDataMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityDataMessage) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EntityDataMessage) GetHealth() float32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *EntityDataMessage) GetEnergy() float32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *EntityDataMessage) GetXPos() float32 {
	if x != nil {
		return x.XPos
	}
	return 0
}

func (x *EntityDataMessage) GetYPos() float32 {
	if x != nil {
		return x.YPos
	}
	return 0
}

func (x *EntityDataMessage) GetZPos() float32 {
	if x != nil {
		return x.ZPos
	}
	return 0
}

type IdMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdMessage) Reset() {
	*x = IdMessage{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdMessage) ProtoMessage() {}

func (x *IdMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdMessage.ProtoReflect.Descriptor instead.
func (*IdMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *IdMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Chat
	//	*Packet_Credential
	//	*Packet_Id
	//	*Packet_EntityData
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetCredential() *CredentialMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Credential); ok {
			return x.Credential
		}
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetEntityData() *EntityDataMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_EntityData); ok {
			return x.EntityData
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type Packet_Credential struct {
	Credential *CredentialMessage `protobuf:"bytes,3,opt,name=credential,proto3,oneof"`
}

type Packet_Id struct {
	Id *IdMessage `protobuf:"bytes,4,opt,name=id,proto3,oneof"`
}

type Packet_EntityData struct {
	EntityData *EntityDataMessage `protobuf:"bytes,5,opt,name=entityData,proto3,oneof"`
}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_Credential) isPacket_Msg() {}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_EntityData) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"w\n" +
	"\vChatMessage\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\x04R\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\x04R\trecipient\x12\x18\n" +
	"\achannel\x18\x03 \x01(\x04R\achannel\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"?\n" +
	"\x11CredentialMessage\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"\xb5\x01\n" +
	"\x11EntityDataMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06health\x18\x03 \x01(\x02R\x06health\x12\x16\n" +
	"\x06energy\x18\x04 \x01(\x02R\x06energy\x12\x13\n" +
	"\x05x_pos\x18\x05 \x01(\x02R\x04xPos\x12\x13\n" +
	"\x05y_pos\x18\x06 \x01(\x02R\x04yPos\x12\x13\n" +
	"\x05z_pos\x18\a \x01(\x02R\x04zPos\"\x1b\n" +
	"\tIdMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xfa\x01\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12*\n" +
	"\x04chat\x18\x02 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12<\n" +
	"\n" +
	"credential\x18\x03 \x01(\v2\x1a.packets.CredentialMessageH\x00R\n" +
	"credential\x12$\n" +
	"\x02id\x18\x04 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12<\n" +
	"\n" +
	"entityData\x18\x05 \x01(\v2\x1a.packets.EntityDataMessageH\x00R\n" +
	"entityDataB\x05\n" +
	"\x03msgB\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_packets_proto_goTypes = []any{
	(*ChatMessage)(nil),       // 0: packets.ChatMessage
	(*CredentialMessage)(nil), // 1: packets.CredentialMessage
	(*EntityDataMessage)(nil), // 2: packets.EntityDataMessage
	(*IdMessage)(nil),         // 3: packets.IdMessage
	(*Packet)(nil),            // 4: packets.Packet
}
var file_packets_proto_depIdxs = []int32{
	0, // 0: packets.Packet.chat:type_name -> packets.ChatMessage
	1, // 1: packets.Packet.credential:type_name -> packets.CredentialMessage
	3, // 2: packets.Packet.id:type_name -> packets.IdMessage
	2, // 3: packets.Packet.entityData:type_name -> packets.EntityDataMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[4].OneofWrappers = []any{
		(*Packet_Chat)(nil),
		(*Packet_Credential)(nil),
		(*Packet_Id)(nil),
		(*Packet_EntityData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
